services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/devdb
      SPRING_DATASOURCE_USERNAME: dev
      SPRING_DATASOURCE_PASSWORD: dev
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: 8xS7vK9mP2nQ4wR5tY6uI7oP8aS9dF0gH1jK2lZ3xC4vB5nM6qW7eR8tY9uI0oP1aS2dF3gH4jK5lZ6xC7vB8nM9qW0eR1tY2u==
      JWT_EXPIRATION: 86400000
      JWT_COOKIENAME: token
    depends_on:
      - db
    networks:
      - app-network


  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-local:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d devdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres-data-local:

networks:
  app-network:
    driver: bridge